name: "PR Checks Components - Unit Tests"

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/cdc-react/**
    
jobs:
  unit-test:
    name: "Run Vitest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: yarn
      - name: Build Icons
        run: yarn build:cdc-react-icons
      - name: Vitest
        working-directory: packages/cdc-react
        run: yarn test
