name: "Publish CDC React Components to NPM"

on:
  push:
    tags:
      - cdc-react-**

defaults:
  run:
    working-directory: packages/cdc-react

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org" # Allows NPM credentials to properly be configured.
      - name: Install prod dependencies  
        run: yarn install --production
      - name: Build package
        run: yarn build
      - name: Publish to NPM
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CDC_REACT_NPM_TOKEN }}
