name: "Release CDC React Icons Library"

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - packages/cdc-react-icons/**

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        with: 
          release-type: node
          package-name: cdc-react-icons
          token: ${{secrets.GITHUB_TOKEN}}
          path: packages/cdc-react-icons
          monorepo-tags: true
  publish-to-npm:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.released }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org" # Allows NPM credentials to properly be configured.
      - name: Install dependencies  
        run: yarn install
      - name: Build package
        run: yarn build
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CDC_REACT_NPM_TOKEN }}
        run: npm publish
