name: "Release CDC React Icons Library"

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - packages/cdc-react-icons/**

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with: 
          release-type: node
          package-name: cdc-react-icons
          token: ${{secrets.GITHUB_TOKEN}}
          path: packages/cdc-react-icons
          monorepo-tags: true
