name: "Release CDC React Library"

on:
  push:
    branches: 
      - main
    paths:
      - packages/cdc-react/**

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with: 
          release-type: node
          package-name: cdc-react
          token: ${{secrets.GITHUB_TOKEN}}
          path: packages/cdc-react
          monorepo-tags: true
          release-as: "0.7.0"
